server:
  port: ${SERVER_PORT}

spring:
  webflux:
    base-path: /reports
  application:
    name: "reports-service"
  devtools:
    add-properties: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: "UTC"

aws:
  region: ${AWS_REGION}
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME}
  sqs:
    estado-solicitud:
      region: ${AWS_REGION}
      queueUrl: ${AWS_SQS_ESTADO_SOLICITUD_QUEUE_URL}
      waitTimeSeconds: 20
      visibilityTimeoutSeconds: 30
      maxNumberOfMessages: 10
      numberOfThreads: 1

adapter:
  sqs:
    region: ${AWS_REGION}
    queueUrl: ${AWS_SQS_NOTIFICACIONES_QUEUE_URL}
management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: ${JWT_SECRET:test12223ADSUYDASIJAS61526132-123123123gsaug}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

logging:
  level:
    com.crediya: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}